// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2dGTVZk4B1eO203aglflUSAvsN61Bzw',
    appId: '1:84298571135:web:1f2ad940c9dfdd69da4e4a',
    messagingSenderId: '84298571135',
    projectId: 'todo-afd80',
    authDomain: 'todo-afd80.firebaseapp.com',
    storageBucket: 'todo-afd80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVUFoBJsUAGru8hpLopWtU9YLBNmRN-k',
    appId: '1:84298571135:android:c88a5bd98fae2f31da4e4a',
    messagingSenderId: '84298571135',
    projectId: 'todo-afd80',
    storageBucket: 'todo-afd80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDByZxoKRumeRdAU4yo1CZkCDh25815yhs',
    appId: '1:84298571135:ios:4cbf564ff310b677da4e4a',
    messagingSenderId: '84298571135',
    projectId: 'todo-afd80',
    storageBucket: 'todo-afd80.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDByZxoKRumeRdAU4yo1CZkCDh25815yhs',
    appId: '1:84298571135:ios:8472dafa4501bca8da4e4a',
    messagingSenderId: '84298571135',
    projectId: 'todo-afd80',
    storageBucket: 'todo-afd80.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
